plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hp2.mobile'
    compileSdk 36
    ndkVersion '28.2.13676358'

    defaultConfig {
        applicationId "com.hp2.mobile"
        minSdk 26
        targetSdk 36
        versionCode 5
        versionName "0.5.0-g4a-dev"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    signingConfigs {
        development {
            storeFile file('../dev-signing.keystore')
            storePassword 'hp2mobiledev'
            keyAlias 'hp2-dev'
            keyPassword 'hp2mobiledev'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.development
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            ndk.debugSymbolLevel = 'SYMBOL_TABLE'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        prefab true
    }

    packaging {
        jniLibs.useLegacyPackaging = false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.16.0'
    implementation 'androidx.games:games-activity:4.4.1'
}
